apiVersion: v1
kind: Pod
metadata:
  name: aspnet-mssql
  labels:
    app: aspnet-mssql
spec:
  restartPolicy: Always
  containers:
    - name: web
      image: aspnet-app
      ports:
        - containerPort: 80
          hostPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 30
    - name: db
      image: mcr.microsoft.com/azure-sql-edge:1.0.4
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "example_123"
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P example_123 -Q 'SELECT 1'
        initialDelaySeconds: 20
        periodSeconds: 30
