apiVersion: v1
kind: Pod
metadata:
  name: django-postgres
  labels:
    app: django-postgres
spec:
  restartPolicy: Always
  containers:
    - name: db
      image: postgres
      env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
    - name: web
      image: django-postgres-app
      command:
        - python
        - manage.py
        - runserver
        - 0.0.0.0:8000
      env:
        - name: POSTGRES_NAME
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 8000
          hostPort: 8000
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 30
  volumes:
    - name: db-data
      emptyDir: {}
