# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wordpress
  name: wpod
spec:
  containers:
  - args:
    - mariadbd
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: somewordpress
    - name: MYSQL_USER
      value: wordpress
    - name: MYSQL_PASSWORD
      value: wordpress
    - name: MYSQL_DATABASE
      value: wordpress
    image: docker.io/library/mariadb:latest
    name: db
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: data-pvc
  - args:
    - apache2-foreground
    env:
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    - name: WORDPRESS_DB_PASSWORD
      value: wordpress
    image: docker.io/library/wordpress:latest
    name: web
    volumeMounts:
    - mountPath: /var/www/html
      name: wp-pvc
  restartPolicy: Always
  volumes:
  - name: data-pvc
    persistentVolumeClaim:
      claimName: data
  - name: wp-pvc
    persistentVolumeClaim:
      claimName: web

