apiVersion: v1
kind: Pod
metadata:
  name: sparkjava-mysql
  labels:
    app: sparkjava-mysql
spec:
  restartPolicy: Always
  containers:
    - name: db
      image: mariadb:10.6.4-focal
      env:
        - name: MYSQL_DATABASE
          value: "example"
        - name: MYSQL_ROOT_PASSWORD
          value: "example"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
    - name: backend
      image: sparkjava-mysql-backend
      ports:
        - containerPort: 8080
          hostPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 30
  volumes:
    - name: db-data
      emptyDir: {}
