apiVersion: v1
kind: Pod
metadata:
  name: apache-php-web
spec:
  containers:
  - name: web
    image: apache-php-web:latest
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - name: app-volume
      mountPath: /var/www/html/
  volumes:
  - name: app-volume
    hostPath:
      path: ./app
