name: flask-redis
services:
  redis:
    image: docker.io/redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
  web:
    container_name: flask-app
    build:
      context: .
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      - redis
