apiVersion: v1
kind: Pod
metadata:
  name: nginx-golang-mysql
  labels:
    app: nginx-golang-mysql
spec:
  restartPolicy: Always
  containers:
    - name: db
      image: mariadb:10-focal
      args:
        - "--default-authentication-plugin=mysql_native_password"
      env:
        - name: MYSQL_DATABASE
          value: "example"
        - name: MYSQL_ROOT_PASSWORD
          value: "example"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
    - name: backend
      image: nginx-golang-mysql-backend
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: "/"
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 30
    - name: proxy
      image: nginx:latest
      ports:
        - containerPort: 80
          hostPort: 80
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
  volumes:
    - name: db-data
      emptyDir: {}
    - name: nginx-config
      hostPath:
        path: ./proxy
