apiVersion: v1
kind: Pod
metadata:
  name: spring-postgres
  labels:
    app: spring-postgres
spec:
  restartPolicy: Always
  containers:
    - name: db
      image: postgres
      env:
        - name: POSTGRES_DB
          value: "example"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "example"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
    - name: backend
      image: spring-postgres-backend
      env:
        - name: POSTGRES_DB
          value: "example"
      ports:
        - containerPort: 8080
          hostPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 30
  volumes:
    - name: db-data
      emptyDir: {}
