apiVersion: v1
kind: Pod
metadata:
  name: fastapi
spec:
  containers:
    - name: api
      image: fastapi-app
      env:
        - name: PORT
          value: "8000"
      ports:
        - containerPort: 8000
          hostPort: 8000
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 30