apiVersion: v1
kind: Pod
metadata:
  name: elk
  labels:
    app: elk
spec:
  restartPolicy: Always
  containers:
    - name: elasticsearch
      image: elasticsearch:7.16.1
      env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
      ports:
        - containerPort: 9200
          hostPort: 9200
        - containerPort: 9300
          hostPort: 9300
      livenessProbe:
        httpGet:
          path: /_cluster/health
          port: 9200
        initialDelaySeconds: 20
        periodSeconds: 30
    - name: logstash
      image: logstash:7.16.1
      env:
        - name: discovery.seed_hosts
          value: logstash
        - name: LS_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
      command:
        - logstash
        - -f
        - /usr/share/logstash/pipeline/logstash-nginx.config
      ports:
        - containerPort: 5000
          hostPort: 5000
        - containerPort: 5044
          hostPort: 5044
        - containerPort: 9600
          hostPort: 9600
      volumeMounts:
        - name: logstash-pipeline
          mountPath: /usr/share/logstash/pipeline/logstash-nginx.config
          subPath: logstash-nginx.config
        - name: logstash-nginx-log
          mountPath: /home/nginx.log
          subPath: nginx.log
    - name: kibana
      image: kibana:7.16.1
      ports:
        - containerPort: 5601
          hostPort: 5601
  volumes:
    - name: logstash-pipeline
      hostPath:
        path: ./logstash/pipeline
    - name: logstash-nginx-log
      hostPath:
        path: ./logstash
