services:
  frontend:
    image: traefik:latest
    container_name: traefik
    command: --providers.docker --entrypoints.web.address=:8080 --providers.docker.exposedbydefault=false
    ports:
      # The HTTP port
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - backend
  backend:
    build: .
    image: backend
    container_name: backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go.rule=Path(`/`)"
      - "traefik.http.services.go.loadbalancer.server.port=8080"
