apiVersion: v1
kind: Pod
metadata:
  name: nextcloud-postgres
  labels:
    app: nextcloud-postgres
spec:
  restartPolicy: Always
  containers:
    - name: db
      image: postgres:alpine
      env:
        - name: POSTGRES_PASSWORD
          value: "nextcloud"
        - name: POSTGRES_DB
          value: "nextcloud"
        - name: POSTGRES_USER
          value: "nextcloud"
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
    - name: nc
      image: nextcloud:apache
      env:
        - name: POSTGRES_HOST
          value: "db"
        - name: POSTGRES_PASSWORD
          value: "nextcloud"
        - name: POSTGRES_DB
          value: "nextcloud"
        - name: POSTGRES_USER
          value: "nextcloud"
      ports:
        - containerPort: 80
          hostPort: 80
      volumeMounts:
        - name: nc-data
          mountPath: /var/www/html
  volumes:
    - name: db-data
      emptyDir: {}
    - name: nc-data
      emptyDir: {}
