apiVersion: v1
kind: Pod
metadata:
  name: nginx-aspnet-mysql
  labels:
    app: nginx-aspnet-mysql
spec:
  restartPolicy: Always
  containers:
    - name: db
      image: mariadb:10-focal
      args:
        - "--default-authentication-plugin=mysql_native_password"
      env:
        - name: MYSQL_DATABASE
          value: "example"
        - name: MYSQL_ROOT_PASSWORD
          value: "example"
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
    - name: backend
      image: nginx-aspnet-backend
      env:
        - name: ASPNETCORE_URLS
          value: "http://+:8000"
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: "/"
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 30
    - name: proxy
      image: nginx-aspnet-proxy
      ports:
        - containerPort: 80
          hostPort: 80
  volumes:
    - name: db-data
      emptyDir: {}
