apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pgadmin
  labels:
    app: postgresql-pgadmin
spec:
  restartPolicy: Always
  containers:
    - name: postgres
      image: postgres:latest
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-env
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-env
              key: POSTGRES_PW
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-env
              key: POSTGRES_DB
      ports:
        - containerPort: 5432
          hostPort: 5432
    - name: pgadmin
      image: dpage/pgadmin4:latest
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: postgres-env
              key: PGADMIN_MAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-env
              key: PGADMIN_PW
      ports:
        - containerPort: 80
          hostPort: 5050
