apiVersion: v1
kind: Pod
metadata:
  name: gitea-pg
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_DB
          value: gitea
        - name: POSTGRES_USER
          value: gitea
        - name: POSTGRES_PASSWORD
          value: gitea
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      resources: {}
    
    - name: gitea
      image: gitea/gitea:latest
      env:
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: localhost:5432
        - name: DB_NAME
          value: gitea
        - name: DB_USER
          value: gitea
        - name: DB_PASSWD
          value: gitea
      ports:
        - containerPort: 3000
          hostPort: 3000
        - containerPort: 2222
          hostPort: 2222
      volumeMounts:
        - name: gitea-data
          mountPath: /data
      resources: {}

  volumes:
    - name: postgres-data
      emptyDir: {}
    - name: gitea-data
      emptyDir: {}
