apiVersion: v1
kind: Pod
metadata:
  name: react-rust-postgres
  labels:
    app: react-rust-postgres
spec:
  restartPolicy: Always
  containers:
    - name: db
      image: postgres:12-alpine
      env:
        - name: POSTGRES_PASSWORD
          value: "mysecretpassword"
      ports:
        - containerPort: 5432
          hostPort: 5432
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
    - name: backend
      image: react-rust-postgres-backend
      env:
        - name: ADDRESS
          value: "0.0.0.0:8000"
        - name: RUST_LOG
          value: "debug"
        - name: PG_DBNAME
          value: "postgres"
        - name: PG_HOST
          value: "db"
        - name: PG_USER
          value: "postgres"
        - name: PG_PASSWORD
          value: "mysecretpassword"
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: "/"
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 30
    - name: frontend
      image: react-rust-postgres-frontend
      ports:
        - containerPort: 3000
          hostPort: 3000
      livenessProbe:
        httpGet:
          path: "/"
          port: 3000
        initialDelaySeconds: 10
        periodSeconds: 30
  volumes:
    - name: db-data
      emptyDir: {}
